# network vars | used in ansible playbook - these should not be changed
ten_network: "sepolia"
loki_metrics_uri: "https://metrics.ten.xyz:3443/loki/api/v1/push"
loki_username: "ten"
loki_password: "ten"
node_version: "v1.4.3"
enclave_docker_build_tag: "testnetobscuronet.azurecr.io/obscuronet/enclave:{{ node_version }}"
host_docker_build_tag: "testnetobscuronet.azurecr.io/obscuronet/host:{{ node_version }}"
l2_batch_interval: "1s"
l2_max_batch_interval: "1s"
l2_rollup_interval: "15m"
l1_chain_id: 11155111
message_bus_contract_addr: "0xAdF463ACDDc9FF5df46F40c01D8a75488422Bd59"
l1_start_hash: "0x2cb95e4289e19749b413a9dcca6a849034c182fc4c5bdbdb2fad9f85e1c8556c"
sequencer_addr: "sepolia-sequencer.ten.xyz:10000"
enclave_registry_addr: "0x2e042cdb4a2E35333b8Da341bcad7563EA114532"
da_registry_addr: "0x93a36E0310f8177761a883dEae131AB6a4bFCFB6"
cross_chain_addr: "0x27785cD99D88a7dd642de3a62bfdc06E6B1C6817"
network_config_addr: "0xD6F4ce9Dc67792245c787C83BF5f39051106C2FF"
bridge_contract_addr: "0xa1FBcE3996ca2B919A6e0e6448d85B9f17cF3286"
rollup_retry_interval: "6h"
system_contracts_upgrader: "0xA58C60cc047592DE97BF1E8d2f225Fc5D959De77"
num_enclaves: 1
