# network vars | used in ansible playbook - these should not be changed
ten_network: "sepolia"
loki_metrics_uri: "https://metrics.ten.xyz:3443/loki/api/v1/push"
loki_username: "ten"
loki_password: "ten"
node_version: "v1.1.0"
enclave_docker_build_tag: "testnetobscuronet.azurecr.io/obscuronet/enclave:{{ node_version }}"
host_docker_build_tag: "testnetobscuronet.azurecr.io/obscuronet/host:{{ node_version }}"
l2_batch_interval: "1s"
l2_max_batch_interval: "1s"
l2_rollup_interval: "15m"
l1_chain_id: 11155111
message_bus_contract_addr: "0x56F82aa236260Db8E2e4E5cB7d34343e56CBeBC6"
l1_start_hash: "0x266282441dec35683b9df01d59f77e7a242ba1a27c6b14ac1a0b70c4d5f858f4"
sequencer_addr: "obscuronode-0-sepolia-testnet.uksouth.cloudapp.azure.com:10000"
enclave_registry_addr: "0xf5C9DC3Cd143ccaa091C96091C2921973e8cA23E"
da_registry_addr: "0x3babBAF04dC7f7Ab9A8bA9B457eE5193C5b71Aa3"
cross_chain_addr: "0xd00e25525A5eA4B8A50abBe1B1e4201c751d39D0"
network_config_addr: "0x83B9057A5D2faBf9A6B61353f1fb635E661F0823"
